# These are supported funding model platforms

github: [Verdicchio-Andrea]
patreon: andrea
open_collective: ggg
ko_fi: dfgd
tidelift: npm/babel
community_bridge: cloud-foundry
liberapay: dg
issuehunt: sgtt
otechie: derg
lfx_crowdfunding: cloud-foundry
custom: ['link1', 'link2']
